### ISSUE TITLE
Unknown error occurred when adding MQTT integration

### ISSUE THREAD

**Issue by peppepetra** [home-assistant-snap/home-assistant-snap#10]
When trying to add MQTT integration I get:

```
2022-04-08 17:17:31 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 164, in post
    return await super().post(request, flow_id)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/homeassistant/components/mqtt/config_flow.py", line 61, in async_step_broker
    can_connect = await self.hass.async_add_executor_job(
  File "/snap/home-assistant-snap/487/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/homeassistant/components/mqtt/config_flow.py", line 328, in try_connection
    import paho.mqtt.client as mqtt
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/paho/mqtt/client.py", line 72, in <module>
    import dns.resolver
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/dns/resolver.py", line 38, in <module>
    import dns.query
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/dns/query.py", line 52, in <module>
    import httpx
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/httpx/__init__.py", line 47, in <module>
    from ._main import main
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/httpx/_main.py", line 10, in <module>
    import rich.console
  File "/snap/home-assistant-snap/487/lib/python3.9/site-packages/rich/__init__.py", line 16, in <module>
    _IMPORT_CWD = os.path.abspath(os.getcwd())
FileNotFoundError: [Errno 2] No such file or directory

```
Am I missing any configuration?

Snap is at latest/stable 2022.2.9

**Comment by jmgiaever** [comment]
Hi,

Sorry my delayed response, but I've been away for +2 weeks. Have you solved it? I'm not using MQTT myself anymore, but I will try to investigate if you still have the problem.

However I did use it before with HA and I had no problem with the integration. To me it seems to be an configuration error;
