### ISSUE TITLE
2024.4.4 broken ZHA

### ISSUE THREAD

**Issue by kevinmcmurtrie** [home-assistant-snap/home-assistant-snap#32]
2024.4.4 was pushed to latest/stable but it has a major bug:
https://github.com/home-assistant/core/issues/115459

```
Logger: homeassistant
Source: /snap/home-assistant-snap/600/lib/python3.12/site-packages/homeassistant/runner.py:146
First occurred: May 6, 2024 at 11:18:30 PM (3002 occurrences)
Last logged: 9:14:14 PM

Error doing job: Exception in callback SerialTransport._read_ready()
ValueError: (11, None) is not a valid NcpResetCode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/serial_asyncio_fast/__init__.py", line 137, in _read_ready
    self._protocol.data_received(data)
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/bellows/uart.py", line 84, in data_received
    self.frame_received(frame)
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/bellows/uart.py", line 119, in frame_received
    self.rstack_frame_received(data)
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/bellows/uart.py", line 160, in rstack_frame_received
    code, version = self._get_error_code(data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/bellows/uart.py", line 193, in _get_error_code
    return t.NcpResetCode(data[2]), data[1]
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/bellows/types/basic.py", line 216, in __call__
    return super().__call__(value, names, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/enum.py", line 757, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/enum.py", line 1179, in __new__
    raise exc
  File "/usr/lib/python3.12/enum.py", line 1156, in __new__
    result = cls._missing_(value)
             ^^^^^^^^^^^^^^^^^^^^
  File "/snap/home-assistant-snap/600/lib/python3.12/site-packages/bellows/types/basic.py", line 225, in _missing_
    new = int_type.__new__(cls, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'tuple'

```

**Comment by jmgiaever** [comment]
We are aware. See https://github.com/giaever-online-iot/home-assistant-snap/issues/31#issuecomment-2101642954

**Comment by kevinmcmurtrie** [comment]
This bug is only about the 'latest/stable' tag not referring to a stable release.

**Comment by jmgiaever** [comment]
Well, there will be an update when there's a fix. 

It's impossible to know every bug in advance. I'm following the HA Core releases. When they consider a minor version stable, we do too. 2024.4 was the final patch release for that minor.

You can roll back to 2024.3 and wait for the final release of 2024.5
